package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */


import DAO.FuncionarioDAO;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import model.Funcionario;

/**
 *
 * @author joaoh
 */
public class GerenciadorDeFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerenciadorDeFuncionarios
     */
    private Long funcionarioEditandoId;
    MaskFormatter mfdata;
    public GerenciadorDeFuncionarios() { 
        
        try {
            mfdata = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            System.out.println("Ocorreu um erro na criação da máscara");
        }
        initComponents();
        popularFuncionarios();
        abrirOpcoes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        salarioFuncionario = new javax.swing.JTextField();
        cadastrarFuncionario = new javax.swing.JButton();
        departamentoFuncionario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cargoFuncionario = new javax.swing.JTextField();
        emailFuncionario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        telefoneFuncionario = new javax.swing.JTextField();
        enderecoFuncionario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jDataText = new javax.swing.JFormattedTextField(mfdata);
        cpfFuncionario = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nomeFuncionario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();
        editarFuncionario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        queryFuncInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nomeFuncionarioEdit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cpfFuncionarioEdit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salarioFuncionarioEdit = new javax.swing.JTextField();
        jDataTextEdit = new javax.swing.JFormattedTextField(mfdata);
        departamentoFuncionarioEdit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cargoFuncionarioEdit = new javax.swing.JTextField();
        enderecoFuncionarioEdit = new javax.swing.JTextField();
        emailFuncionarioEdit = new javax.swing.JTextField();
        telefoneFuncionarioEdit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancelarAtualizacao = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        salarioFuncionario1 = new javax.swing.JTextField();
        cadastrarFuncionario1 = new javax.swing.JButton();
        departamentoFuncionario1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cargoFuncionario1 = new javax.swing.JTextField();
        emailFuncionario1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        telefoneFuncionario1 = new javax.swing.JTextField();
        enderecoFuncionario1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jDataText1 = new javax.swing.JFormattedTextField(mfdata);
        cpfFuncionario1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        nomeFuncionario1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProdutos1 = new javax.swing.JTable();
        editarFuncionario1 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        queryFuncInput1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        nomeFuncionarioEdit1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cpfFuncionarioEdit1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        salarioFuncionarioEdit1 = new javax.swing.JTextField();
        jDataTextEdit1 = new javax.swing.JFormattedTextField(mfdata);
        departamentoFuncionarioEdit1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        cargoFuncionarioEdit1 = new javax.swing.JTextField();
        enderecoFuncionarioEdit1 = new javax.swing.JTextField();
        emailFuncionarioEdit1 = new javax.swing.JTextField();
        telefoneFuncionarioEdit1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gerenciador De Funcionários");
        setToolTipText("Gerenciador De Funcionários");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Salário");

        salarioFuncionario.setActionCommand("<Not Set>");
        salarioFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioFuncionarioActionPerformed(evt);
            }
        });

        cadastrarFuncionario.setText("Cadastrar");
        cadastrarFuncionario.setToolTipText("");
        cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioActionPerformed(evt);
            }
        });

        departamentoFuncionario.setActionCommand("<Not Set>");
        departamentoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoFuncionarioActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Departamento");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Cargo");

        cargoFuncionario.setActionCommand("<Not Set>");
        cargoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoFuncionarioActionPerformed(evt);
            }
        });

        emailFuncionario.setActionCommand("<Not Set>");
        emailFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFuncionarioActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Email");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Telefone");

        telefoneFuncionario.setActionCommand("<Not Set>");
        telefoneFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFuncionarioActionPerformed(evt);
            }
        });

        enderecoFuncionario.setActionCommand("<Not Set>");
        enderecoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoFuncionarioActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Endereço");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("D. Nascimento");

        cpfFuncionario.setActionCommand("<Not Set>");
        cpfFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFuncionarioActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("CPF");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Nome");

        nomeFuncionario.setActionCommand("<Not Set>");
        nomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFuncionarioActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 22)); // NOI18N
        jLabel1.setText("CADASTRO DE FUNCIONÁRIOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(nomeFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enderecoFuncionario)
                            .addComponent(jDataText)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefoneFuncionario)
                            .addComponent(cargoFuncionario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departamentoFuncionario)
                            .addComponent(salarioFuncionario))))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDataText, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(enderecoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(telefoneFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(emailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(departamentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(salarioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(cadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Adicionar Funcionários", jPanel1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Clique com o botão direito em algum item da tabela para abrir as opções");

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF", "Data de Nascimento", "Endereço", "Telefone", "Email", "Cargo", "Departamento", "Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFuncionarios);

        editarFuncionario.setText("Atualizar");
        editarFuncionario.setToolTipText("");
        editarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFuncionarioActionPerformed(evt);
            }
        });

        jLabel10.setText("BUSQUE OS FUNCIONÁRIOS");

        queryFuncInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryFuncInputActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Cargo");

        nomeFuncionarioEdit.setActionCommand("<Not Set>");
        nomeFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFuncionarioEditActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Departamento");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("CPF");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Salário");

        cpfFuncionarioEdit.setActionCommand("<Not Set>");
        cpfFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFuncionarioEditActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("D. Nascimento");

        salarioFuncionarioEdit.setActionCommand("<Not Set>");
        salarioFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioFuncionarioEditActionPerformed(evt);
            }
        });

        departamentoFuncionarioEdit.setActionCommand("<Not Set>");
        departamentoFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoFuncionarioEditActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Endereço");

        cargoFuncionarioEdit.setActionCommand("<Not Set>");
        cargoFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoFuncionarioEditActionPerformed(evt);
            }
        });

        enderecoFuncionarioEdit.setActionCommand("<Not Set>");
        enderecoFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoFuncionarioEditActionPerformed(evt);
            }
        });

        emailFuncionarioEdit.setActionCommand("<Not Set>");
        emailFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFuncionarioEditActionPerformed(evt);
            }
        });

        telefoneFuncionarioEdit.setActionCommand("<Not Set>");
        telefoneFuncionarioEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFuncionarioEditActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Telefone");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Email");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Nome");

        cancelarAtualizacao.setText("Cancelar");
        cancelarAtualizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAtualizacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancelarAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(editarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(351, 351, 351)
                                        .addComponent(jLabel10))
                                    .addComponent(queryFuncInput, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel9))
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nomeFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel12))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(salarioFuncionarioEdit)
                                            .addComponent(cargoFuncionarioEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enderecoFuncionarioEdit, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(45, 45, 45)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telefoneFuncionarioEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(departamentoFuncionarioEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDataTextEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cpfFuncionarioEdit))))
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryFuncInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cpfFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(emailFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departamentoFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cargoFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDataTextEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(enderecoFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(salarioFuncionarioEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cancelarAtualizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar Funcionários", jPanel2);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Salário");

        salarioFuncionario1.setActionCommand("<Not Set>");
        salarioFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioFuncionario1ActionPerformed(evt);
            }
        });

        cadastrarFuncionario1.setText("Cadastrar");
        cadastrarFuncionario1.setToolTipText("");
        cadastrarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionario1ActionPerformed(evt);
            }
        });

        departamentoFuncionario1.setActionCommand("<Not Set>");
        departamentoFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoFuncionario1ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setText("Departamento");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Cargo");

        cargoFuncionario1.setActionCommand("<Not Set>");
        cargoFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoFuncionario1ActionPerformed(evt);
            }
        });

        emailFuncionario1.setActionCommand("<Not Set>");
        emailFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFuncionario1ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Email");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setText("Telefone");

        telefoneFuncionario1.setActionCommand("<Not Set>");
        telefoneFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFuncionario1ActionPerformed(evt);
            }
        });

        enderecoFuncionario1.setActionCommand("<Not Set>");
        enderecoFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoFuncionario1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("Endereço");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("D. Nascimento");

        cpfFuncionario1.setActionCommand("<Not Set>");
        cpfFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFuncionario1ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("CPF");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setText("Nome");

        nomeFuncionario1.setActionCommand("<Not Set>");
        nomeFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFuncionario1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel31.setFont(new java.awt.Font("Palatino Linotype", 1, 22)); // NOI18N
        jLabel31.setText("CADASTRO DE FUNCIONÁRIOS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cpfFuncionario1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(nomeFuncionario1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(enderecoFuncionario1)
                            .addComponent(jDataText1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cadastrarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailFuncionario1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefoneFuncionario1)
                            .addComponent(cargoFuncionario1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(departamentoFuncionario1)
                            .addComponent(salarioFuncionario1))))
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(nomeFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(cpfFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDataText1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(enderecoFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(telefoneFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(emailFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(cargoFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(departamentoFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(salarioFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cadastrarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane2.addTab("Adicionar Funcionários", jPanel4);

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel32.setText("Clique com o botão direito em algum item da tabela para abrir as opções");

        tabelaProdutos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "CPF", "Data de Nascimento", "Endereço", "Telefone", "Email", "Cargo", "Departamento", "Salário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaProdutos1);

        editarFuncionario1.setText("Atualizar");
        editarFuncionario1.setToolTipText("");
        editarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFuncionario1ActionPerformed(evt);
            }
        });

        jLabel33.setText("BUSQUE OS FUNCIONÁRIOS");

        queryFuncInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queryFuncInput1ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel34.setText("Cargo");

        nomeFuncionarioEdit1.setActionCommand("<Not Set>");
        nomeFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFuncionarioEdit1ActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setText("Departamento");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel36.setText("CPF");

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel37.setText("Salário");

        cpfFuncionarioEdit1.setActionCommand("<Not Set>");
        cpfFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFuncionarioEdit1ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setText("D. Nascimento");

        salarioFuncionarioEdit1.setActionCommand("<Not Set>");
        salarioFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioFuncionarioEdit1ActionPerformed(evt);
            }
        });

        departamentoFuncionarioEdit1.setActionCommand("<Not Set>");
        departamentoFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoFuncionarioEdit1ActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel39.setText("Endereço");

        cargoFuncionarioEdit1.setActionCommand("<Not Set>");
        cargoFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoFuncionarioEdit1ActionPerformed(evt);
            }
        });

        enderecoFuncionarioEdit1.setActionCommand("<Not Set>");
        enderecoFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoFuncionarioEdit1ActionPerformed(evt);
            }
        });

        emailFuncionarioEdit1.setActionCommand("<Not Set>");
        emailFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFuncionarioEdit1ActionPerformed(evt);
            }
        });

        telefoneFuncionarioEdit1.setActionCommand("<Not Set>");
        telefoneFuncionarioEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFuncionarioEdit1ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel40.setText("Telefone");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel41.setText("Email");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel42.setText("Nome");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(351, 351, 351)
                                        .addComponent(jLabel33))
                                    .addComponent(queryFuncInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel42)
                                            .addComponent(jLabel41))
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nomeFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel34)
                                            .addComponent(jLabel39)
                                            .addComponent(jLabel37))
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(salarioFuncionarioEdit1)
                                            .addComponent(cargoFuncionarioEdit1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(enderecoFuncionarioEdit1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(45, 45, 45)))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(telefoneFuncionarioEdit1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(departamentoFuncionarioEdit1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jDataTextEdit1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cpfFuncionarioEdit1))))
                        .addGap(27, 27, 27))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(queryFuncInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(nomeFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(cpfFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(emailFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41))
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departamentoFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(cargoFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDataTextEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(enderecoFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(salarioFuncionarioEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editarFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Editar Funcionários", jPanel6);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salarioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioFuncionarioActionPerformed

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        cadastrarFuncionario();
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void departamentoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoFuncionarioActionPerformed

    private void cargoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoFuncionarioActionPerformed

    private void emailFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFuncionarioActionPerformed

    private void telefoneFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFuncionarioActionPerformed

    private void enderecoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoFuncionarioActionPerformed

    private void cpfFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFuncionarioActionPerformed

    private void nomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncionarioActionPerformed

    private void telefoneFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFuncionarioEditActionPerformed

    private void emailFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFuncionarioEditActionPerformed

    private void enderecoFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoFuncionarioEditActionPerformed

    private void cargoFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoFuncionarioEditActionPerformed

    private void departamentoFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoFuncionarioEditActionPerformed

    private void salarioFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioFuncionarioEditActionPerformed

    private void cpfFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFuncionarioEditActionPerformed

    private void nomeFuncionarioEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFuncionarioEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncionarioEditActionPerformed

    private void queryFuncInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryFuncInputActionPerformed

    }//GEN-LAST:event_queryFuncInputActionPerformed

    private void editarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFuncionarioActionPerformed
        editarFuncionario();
    }//GEN-LAST:event_editarFuncionarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limparCamposEdicao();
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        List<Funcionario> funcionarios;
        try {
            funcionarios = funcionarioDAO.buscarPorNome(queryFuncInput.getText());
            popularProdutosPorNome(funcionarios);
        } catch (Exception ex) {
            Logger.getLogger(VendaItensInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salarioFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioFuncionario1ActionPerformed

    private void cadastrarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarFuncionario1ActionPerformed

    private void departamentoFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoFuncionario1ActionPerformed

    private void cargoFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoFuncionario1ActionPerformed

    private void emailFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFuncionario1ActionPerformed

    private void telefoneFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFuncionario1ActionPerformed

    private void enderecoFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoFuncionario1ActionPerformed

    private void cpfFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFuncionario1ActionPerformed

    private void nomeFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncionario1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarFuncionario1ActionPerformed

    private void queryFuncInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryFuncInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queryFuncInput1ActionPerformed

    private void nomeFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFuncionarioEdit1ActionPerformed

    private void cpfFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfFuncionarioEdit1ActionPerformed

    private void salarioFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioFuncionarioEdit1ActionPerformed

    private void departamentoFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoFuncionarioEdit1ActionPerformed

    private void cargoFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoFuncionarioEdit1ActionPerformed

    private void enderecoFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoFuncionarioEdit1ActionPerformed

    private void emailFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFuncionarioEdit1ActionPerformed

    private void telefoneFuncionarioEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFuncionarioEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFuncionarioEdit1ActionPerformed

    private void cancelarAtualizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAtualizacaoActionPerformed
        limparCamposEdicao();
    }//GEN-LAST:event_cancelarAtualizacaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarFuncionario;
    private javax.swing.JButton cadastrarFuncionario1;
    private javax.swing.JButton cancelarAtualizacao;
    private javax.swing.JTextField cargoFuncionario;
    private javax.swing.JTextField cargoFuncionario1;
    private javax.swing.JTextField cargoFuncionarioEdit;
    private javax.swing.JTextField cargoFuncionarioEdit1;
    private javax.swing.JTextField cpfFuncionario;
    private javax.swing.JTextField cpfFuncionario1;
    private javax.swing.JTextField cpfFuncionarioEdit;
    private javax.swing.JTextField cpfFuncionarioEdit1;
    private javax.swing.JTextField departamentoFuncionario;
    private javax.swing.JTextField departamentoFuncionario1;
    private javax.swing.JTextField departamentoFuncionarioEdit;
    private javax.swing.JTextField departamentoFuncionarioEdit1;
    private javax.swing.JButton editarFuncionario;
    private javax.swing.JButton editarFuncionario1;
    private javax.swing.JTextField emailFuncionario;
    private javax.swing.JTextField emailFuncionario1;
    private javax.swing.JTextField emailFuncionarioEdit;
    private javax.swing.JTextField emailFuncionarioEdit1;
    private javax.swing.JTextField enderecoFuncionario;
    private javax.swing.JTextField enderecoFuncionario1;
    private javax.swing.JTextField enderecoFuncionarioEdit;
    private javax.swing.JTextField enderecoFuncionarioEdit1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFormattedTextField jDataText;
    private javax.swing.JFormattedTextField jDataText1;
    private javax.swing.JFormattedTextField jDataTextEdit;
    private javax.swing.JFormattedTextField jDataTextEdit1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField nomeFuncionario;
    private javax.swing.JTextField nomeFuncionario1;
    private javax.swing.JTextField nomeFuncionarioEdit;
    private javax.swing.JTextField nomeFuncionarioEdit1;
    private javax.swing.JTextField queryFuncInput;
    private javax.swing.JTextField queryFuncInput1;
    private javax.swing.JTextField salarioFuncionario;
    private javax.swing.JTextField salarioFuncionario1;
    private javax.swing.JTextField salarioFuncionarioEdit;
    private javax.swing.JTextField salarioFuncionarioEdit1;
    private javax.swing.JTable tabelaFuncionarios;
    private javax.swing.JTable tabelaProdutos1;
    private javax.swing.JTextField telefoneFuncionario;
    private javax.swing.JTextField telefoneFuncionario1;
    private javax.swing.JTextField telefoneFuncionarioEdit;
    private javax.swing.JTextField telefoneFuncionarioEdit1;
    // End of variables declaration//GEN-END:variables
        
    public void cadastrarFuncionario() {
        try {
            LocalDate dataNascimento;
            try {
                DateTimeFormatter formatoBrasileiro = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                dataNascimento = LocalDate.parse(jDataText.getText(), formatoBrasileiro);
            } catch (DateTimeParseException e1) {
                try {
                    dataNascimento = LocalDate.parse(jDataText.getText());
                } catch (DateTimeParseException e2) {
                    throw new IllegalArgumentException("Formato de data inválido! Use dd/MM/aaaa ou aaaa-MM-dd");
                }
            }

            Funcionario funcionario = new Funcionario(
                null,
                nomeFuncionario.getText(),
                cpfFuncionario.getText(),
                dataNascimento, 
                enderecoFuncionario.getText(), 
                telefoneFuncionario.getText(),
                emailFuncionario.getText(),
                cargoFuncionario.getText(),
                departamentoFuncionario.getText(),
                Double.parseDouble(salarioFuncionario.getText())
            );
                FuncionarioDAO dao = new FuncionarioDAO();
            try {
                dao.incluir(funcionario);
                JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!\nCPF: " + funcionario.getCpf());
                limparCamposFuncionario();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar funcionário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
            try {
                popularFuncionarios();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao popular Tabela: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido! Use o formato yyyy-MM-dd", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salário deve ser um número válido!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar funcionário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void limparCamposFuncionario() {
        nomeFuncionario.setText("");
        cpfFuncionario.setText("");
        jDataText.setText("");
        enderecoFuncionario.setText("");
        telefoneFuncionario.setText("");
        emailFuncionario.setText("");
        cargoFuncionario.setText("");
        departamentoFuncionario.setText("");
        salarioFuncionario.setText("");
    }
    
    
    public void abrirOpcoes() {
        tabelaFuncionarios.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) { // Verifica se foi duplo clique
                    int row = tabelaFuncionarios.getSelectedRow();
                    if (row != -1) { // Verifica se uma linha foi selecionada
                       mostrarPopupMenu(e);
                    }
                }
            }
        });
    }
    
    public void mostrarPopupMenu(MouseEvent e) {
        int row = tabelaFuncionarios.rowAtPoint(e.getPoint());
        if (row >= 0) {
            tabelaFuncionarios.setRowSelectionInterval(row, row);

            JPopupMenu popupMenu = new JPopupMenu();
            
            JMenuItem verDetalhes = new JMenuItem("Ver Detalhes");
            verDetalhes.addActionListener(ev -> abrirDetalhesFuncionario(row));
            popupMenu.add(verDetalhes);
            
            
            JMenuItem deletarItem = new JMenuItem("Deletar");
            deletarItem.addActionListener(ev -> confirmarDelecao(row));
            popupMenu.add(deletarItem);
            
            JMenuItem editarItem = new JMenuItem("Editar Funcionário");
            editarItem.addActionListener(ev -> preencherCamposEdicao(row));
            popupMenu.add(editarItem);
            
            popupMenu.show(e.getComponent(), e.getX(), e.getY());
        }
    }
    
    public void confirmarDelecao(int rowIndex) {
        Long id = (Long) tabelaFuncionarios.getValueAt(rowIndex, 0);
        String nome = (String) tabelaFuncionarios.getValueAt(rowIndex, 1);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja deletar o funcionário:\n" + nome + " (ID: " + id + ")",
            "Confirmar Deleção",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            deletarFuncionario(id, rowIndex);
        }
    }

    public void deletarFuncionario(Long id, int rowIndex) {
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            ((DefaultTableModel)tabelaFuncionarios.getModel()).removeRow(rowIndex);
            dao.excluir(id);
            JOptionPane.showMessageDialog(this, 
                "Funcionário deletado com sucesso!", 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao deletar: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void abrirDetalhesFuncionario(int rowIndex) {
        // Obtém o modelo da tabela
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();

        // Obtém o ID do funcionário (assumindo que está na coluna 0)
        Long id = (Long) model.getValueAt(rowIndex, 0);

        try {
            // Busca os dados completos do funcionário
            FuncionarioDAO dao = new FuncionarioDAO();
            Funcionario funcionario = dao.buscarPorId(id); // Você precisará implementar este método

            // Cria e exibe um diálogo ou janela com os detalhes
            JOptionPane.showMessageDialog(this,
                "Detalhes do Funcionário:\n\n" +
                "ID: " + funcionario.getId() + "\n" +
                "Nome: " + funcionario.getNome() + "\n" +
                "CPF: " + funcionario.getCpf() + "\n" +
                "Data Nasc.: " + funcionario.getDataNascimento() + "\n" +
                "Cargo: " + funcionario.getCargo(),
                "Detalhes do Funcionário",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erro ao carregar detalhes: " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void popularFuncionarios() {
        try {
            FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
            List<Funcionario> funcionarios = funcionarioDAO.buscarTodos();

            DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionarios.getModel();

            modelo.setRowCount(0);

            for (Funcionario funcionario : funcionarios) {
                modelo.addRow(new Object[]{
                    funcionario.getId(),
                    funcionario.getNome(),
                    funcionario.getCpf(),
                    funcionario.getDataNascimento() != null ? funcionario.getDataNascimento().toString() : "",
                    funcionario.getEndereco(),
                    funcionario.getTelefone(),
                    funcionario.getEmail(),
                    funcionario.getCargo(),
                    funcionario.getDepartamento(),
                    funcionario.getSalario()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar funcionários: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void popularProdutosPorNome(List<Funcionario> funcionarios) {
        try {
            
            DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionarios.getModel();

            modelo.setRowCount(0);

            for (Funcionario funcionario : funcionarios) {
                modelo.addRow(new Object[]{
                    funcionario.getId(),
                    funcionario.getNome(),
                    funcionario.getCpf(),
                    funcionario.getDataNascimento() != null ? funcionario.getDataNascimento().toString() : "",
                    funcionario.getEndereco(),
                    funcionario.getTelefone(),
                    funcionario.getEmail(),
                    funcionario.getCargo(),
                    funcionario.getDepartamento(),
                    funcionario.getSalario()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao carregar funcionários: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void preencherCamposEdicao(int rowIndex) {
        DefaultTableModel model = (DefaultTableModel) tabelaFuncionarios.getModel();
        funcionarioEditandoId = (Long) model.getValueAt(rowIndex, 0);

        nomeFuncionarioEdit.setText((String) model.getValueAt(rowIndex, 1));
        cpfFuncionarioEdit.setText((String) model.getValueAt(rowIndex, 2));

        String dataStr = (String) model.getValueAt(rowIndex, 3);
        if (dataStr != null && !dataStr.isEmpty()) {
            try {
                LocalDate data = LocalDate.parse(dataStr);
                DateTimeFormatter formatoBrasileiro = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                jDataTextEdit.setText(data.format(formatoBrasileiro));
            } catch (DateTimeParseException e) {
                jDataTextEdit.setText(dataStr);
            }
        }

        enderecoFuncionarioEdit.setText((String) model.getValueAt(rowIndex, 4));
        telefoneFuncionarioEdit.setText((String) model.getValueAt(rowIndex, 5));
        emailFuncionarioEdit.setText((String) model.getValueAt(rowIndex, 6));
        cargoFuncionarioEdit.setText((String) model.getValueAt(rowIndex, 7));
        departamentoFuncionarioEdit.setText((String) model.getValueAt(rowIndex, 8));
        salarioFuncionarioEdit.setText(model.getValueAt(rowIndex, 9).toString());
        jTabbedPane1.setSelectedIndex(1);
    }
    
    public void editarFuncionario() {
        if (funcionarioEditandoId == null) {
            JOptionPane.showMessageDialog(this, "Nenhum funcionário selecionado para edição", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            LocalDate dataNascimento;
            try {
                DateTimeFormatter formatoBrasileiro = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                dataNascimento = LocalDate.parse(jDataTextEdit.getText(), formatoBrasileiro);
            } catch (DateTimeParseException e1) {
                try {
                    dataNascimento = LocalDate.parse(jDataTextEdit.getText());
                } catch (DateTimeParseException e2) {
                    throw new IllegalArgumentException("Formato de data inválido! Use dd/MM/aaaa ou aaaa-MM-dd");
                }
            }

            Funcionario funcionario = new Funcionario(
                funcionarioEditandoId,
                nomeFuncionarioEdit.getText(),
                cpfFuncionarioEdit.getText(),
                dataNascimento,
                enderecoFuncionarioEdit.getText(),
                telefoneFuncionarioEdit.getText(),
                emailFuncionarioEdit.getText(),
                cargoFuncionarioEdit.getText(),
                departamentoFuncionarioEdit.getText(),
                Double.parseDouble(salarioFuncionarioEdit.getText())
            );

            FuncionarioDAO dao = new FuncionarioDAO();
            dao.atualizar(funcionario);

            JOptionPane.showMessageDialog(this, "Funcionário atualizado com sucesso!");
            limparCamposEdicao();
            popularFuncionarios();
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido! Use o formato dd/MM/aaaa", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Salário deve ser um número válido!", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void limparCamposEdicao() {
        funcionarioEditandoId = null;
        nomeFuncionarioEdit.setText("");
        cpfFuncionarioEdit.setText("");
        jDataTextEdit.setValue(null); 
        jDataTextEdit.setText("");
        enderecoFuncionarioEdit.setText("");
        telefoneFuncionarioEdit.setText("");
        emailFuncionarioEdit.setText("");
        cargoFuncionarioEdit.setText("");
        departamentoFuncionarioEdit.setText("");
        salarioFuncionarioEdit.setText("");
    }
}
